### ISSUE TITLE
Investigate why dependabot doesnt trigger a PR

### ISSUE THREAD

**Issue by predragnikolic** [sublimelsp/LSP-elm#10]
Currently this project uses elm 1.6.3.
https://github.com/sublimelsp/LSP-elm/blob/bdc4055e1eaa14b215ac4b3a898c974927d5510b/server/package.json#L5

There is a new version on npm 1.7.2
https://www.npmjs.com/package/@elm-tooling/elm-language-server

Everything seems fine in the dependabot LSP-elm configuration. 
https://app.dependabot.com/accounts/sublimelsp

Also clicking the `Bump now` button doesn't make a new PR,
but I expect that it should.

**Comment by rchl** [comment]
In the projects I work with those kind of bots typically create bump PR for devDependencies and for production dependencies they create PRs with lock file updates. But since we are not using range version for production deps, we won't get those, I believe.

Since we have a lock file, we can switch to range rather than explicit version for dependency, I think, but I'll have a look at dependencybot docs first.

**Comment by rchl** [comment]
We're getting PRs now.

I've made a couple of commits on master, including:
 - change version to be a range instead of explicit version. I think this is necessary but not sure. It's fine regardless as lock file makes sure that we use version from lockfile.
 - use local configuration file in the repo (this shouldn't be needed)
 - change name of our wrapper package to not be the same as name of the dependency. I think that was the main problem.

**Comment by rchl** [comment]
I've repeated similar exercise for `lsp-vue`

1) applied `Change name of our wrapper npm package to fix dependabot` (https://github.com/sublimelsp/LSP-vue/commit/97a5fb606594da8c4db368a104aee49ffccc09af) - didn't help
2) applied `Use range for the vls server version` (https://github.com/sublimelsp/LSP-vue/commit/9632cae128ece4c9d8741ada4402c2c279b01233) - didn't help
3) applied `Add dependabot config` (https://github.com/sublimelsp/LSP-vue/commit/091b65750b801ff35a75d2806725c9fd3519cba6) - got PRs

So it's quite confusing. Not sure why adding config would make it work...
I think that having explicit configuration in the repo is better thogh.

Dependabot docs suck. There is no documentation for the config schema so it's not clear what are the defaults and even what options are exactly available.

I've waited at least half an hour between 2) and 3) to make sure that delayed results don't affect my testing.

**Comment by predragnikolic** [comment]
Thanks for taking the time to look at this.
Didn't know that there is a config file for dependabot.

>There is no documentation for the config schema so it's not clear what are the defaults and even what options are exactly available.

I just found the documentation here https://dependabot.com/docs/config-file/
